apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-apk-cache
  namespace: arc-runners
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
