name: Android

on:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, arc-runner-set ]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt install -y sdkmanager
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      # - name: Build SampleApplication
      #   run: ./gradlew --no-daemon build
