name: Devbox

on:
  push:
    branches: [main]

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, arc-runner-set ]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4

      - name: Install xz-utils
        run: sudo apt-get update && sudo apt-get install -y xz-utils

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Run arbitrary commands
        run: devbox run -- echo "done!"

      - name: Run a script called test
        run: devbox run success