name: Docker test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: arc-runner-set
    # container: ghcr.io/actions/actions-runner:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: git status
