name: Docker test
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, arc-runner-set ]
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/podman/stable
      options: --user 1000
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Install devbox
      #   uses: jetify-com/devbox-install-action@v0.11.0
      # - run: devbox global add git
      - run: docker ps
      - run: docker run hello-world
      - run: git status
