name: Docker test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: arc-runner-set
    container: catthehacker/ubuntu:custom-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Install devbox
      #   uses: jetify-com/devbox-install-action@v0.11.0
      # - run: devbox global add git
      - run: docker ps
      - run: git status
