name: Docker test
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, arc-runner-set ]
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/podman/stable
    steps:
      - uses: actions/checkout@v4
      - name: Alias podman as docker
        run: echo "alias docker=podman" >> ~/.bashrc && source ~/.bashrc
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
      - run: podman ps
      - run: docker ps
      - run: docker run hello-world
      - run: git status