name: Nix

on:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, arc-runner-set ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix --version
