name: Nix

on:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, self-hosted ]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          init: none
      - run: sudo chown --recursive "$USER" /nix
      - run: sudo chmod --recursive 777 /nix
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          skip-nix-installation: true
