name: Nix

on:
  push:
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, arc-runner-set ]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
        with:
          init: "none"
      - name: Check and Set Permissions
        run: |
          ls -ld /nix/var/nix/profiles/per-user || true
          sudo chmod -R 755 /nix/var/nix/profiles/per-user || true
          sudo chown -R $USER /nix/var/nix/profiles/per-user || true
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix --version
