name: Nix

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix --version